// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package docker_test

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockTagLister is an autogenerated mock type for the TagLister type
type mockTagLister struct {
	mock.Mock
}

// Tags provides a mock function with given fields: ctx, path
func (_m *mockTagLister) Tags(ctx context.Context, path string) ([]string, error) {
	ret := _m.Called(ctx, path)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
